name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1

    - run: |
        cmake -S . -B Release -G Ninja -DCMAKE_BUILD_TYPE=Release -DBC_USE_OPENMP=OFF -DBUILD_DX11=OFF -DBUILD_SAMPLE=OFF -DBUILD_TOOLS=OFF
        ninja -C Release
